"""add event type and confidence level

Revision ID: 1d5b45880ef4
Revises: b6cb161e4797
Create Date: 2026-09-02 20:51:58.707909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5b45880ef4'
down_revision: Union[str, None] = 'b6cb161e4797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('event_type', sa.String(length=50), nullable=True))
    op.add_column('signals', sa.Column('confidence_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'confidence_level')
    op.drop_column('signals', 'event_type')
    # ### end Alembic commands ###
